In [10]:
import numpy as np

### 배열의 크기 변경  
numpy 배열에서 원소의 개수를 유지한 상태로   
배열의 형태를 변경하려 한다면 `reshape` 메서드를 사용하여 변경할 수 있음  

In [11]:
numpy_array = np.zeros(12)
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
reshape_array = numpy_array.reshape(4, 3)
reshape_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
reshape_array = numpy_array.reshape(2, 6)
reshape_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

numpy 배열의 원소는 개수가 정해져 있기 때문에   
`reshape` 메서드에 하나의 인자로 -1을 넣게되면 다른 인자들을 통해서 추론하여 지정

In [14]:
reshape_array = numpy_array.reshape(6, -1)
reshape_array

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
reshape_array = numpy_array.reshape(3, 1, -1)
reshape_array

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

만약, `reshape` 메서드의 인자들의 곱의 결과가 기존 배열의 원소의 총 합과 다르면 에러가 발생  
-1로 지정한 인자가 있을 때 해당 인자의 곱으로 총합을 계산할 수 없는 경우 에러가 발생

In [16]:
reshape_array = numpy_array.reshape(5, 2) # 배열의 길이가 달라 계산할 수 없는 에러 발생
reshape_array

ValueError: cannot reshape array of size 12 into shape (5,2)

In [17]:
reshape_array = numpy_array.reshape(5, -1) # 배열의 길이가 달라 계산할 수 없는 에러 발생
reshape_array

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

다차원 배열을 무조건 1차원 배열로 변경하려 한다면 `flatten` 이나 `ravel` 메서드를 사용

In [18]:
numpy_matrix = np.empty((3, 4))
numpy_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
numpy_array = numpy_matrix.flatten()
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
numpy_array = numpy_matrix.ravel()
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

배열 사용에서 주의할 점은  
*길이가 5인 1차원 배열*  
*5x1인 2차원 배열*    
*1x5인 2차원 배열*  
서로 각각 다른 배열
(요소의 개수와 내용, 순서가 모두 같더라도 형태가 다르면 다른 배열)

차원을 한 차원 증가시키고자 한다면 `numpy.newaxis` 속성으로 차원을 증가 시킬 수 있음 

In [ ]:
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
newaxis_array = numpy_array[:, np.newaxis]
newaxis_array

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

#### 배열 연결하기  
##### 행의 수나 열의 수가 같은 두개 이상의 배열을 연결하는 방법  
###### - `hstack` : 행의 수가 같은 두 개 이상의 배열을 연결  
###### - `vstack` : 열의 수가 같은 두 개 이상의 배열을 연결  
###### - `dstack` : 행과 열의 수가 같은 두 개 이상의 배열을 연결  
###### - `stack` : dstack의 확장 기능으로 행과 열의 수가 같은 두 개 이상의 배열을 연결  
###### 단, 연결 축을 개발자가 직접 지정  
###### - `r_` : 배열의 요소를 연결, 메서드 인자를 `[]`에 전달함  
###### - `c_` : 행끼리 연결, 최소 2차원의 배열로 연결  
###### - `tile` : 하나의 배열을 여러번 반복하여 연결  

In [ ]:
zeros_array = np.zeros((3, 4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
ones_array = np.ones((3,2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
hstack_array = np.hstack([zeros_array, ones_array])
hstack_array

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

In [ ]:
ones_array = np.ones((2,4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
vstack_array = np.vstack([zeros_array, ones_array])
vstack_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
ones_array = np.ones((3, 3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
dstack_array = np.dstack([zeros_array, ones_array])
dstack_array

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

In [ ]:
stack_array = np.stack([zeros_array, ones_array], axis=1)
stack_array

array([[[0., 0., 0.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [1., 1., 1.]]])

In [ ]:
r_array = np.r_[zeros_array, ones_array]
r_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
c_array = np.c_[zeros_array, ones_array]
c_array

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [ ]:
tile_array = np.tile(zeros_array, 2)
tile_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
tile_array = np.tile(zeros_array, (3, 2)) # 행은 *3 열은 *2가 됨.
tile_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
test_array = np.array([[0., 0., 0., 1., 1.],
      [0., 0., 0., 1., 1.],
      [0., 0., 0., 1., 1.],
      [10., 20., 30., 40., 50.],
      [60., 70., 80., 90., 100.],
      [110., 120.,130., 140., 150.],
      [0., 0., 0., 1., 1.],
      [0., 0., 0., 1., 1.],
      [0., 0., 0., 1., 1.],
      [10., 20., 30., 40., 50.],
      [60., 70., 80., 90., 100.],
      [110., 120., 130., 140., 150.]])
test_array

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [23]:
test1_array = np.zeros((3, 3))
test2_array = np.ones((3, 2))

In [24]:
a_array = np.hstack([test1_array, test2_array])
a_array

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [25]:
test3_array = np.arange(10, 160, 10)
test3_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150])

In [26]:
b_array = test3_array.reshape(3, 5)
b_array


array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [36]:
c_array = np.vstack([a_array,b_array])
c_array

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [38]:
tile_array = np.tile(c_array, (2, 1))
tile_array

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])