### 2차원 그리드 포인트 생성
좌표값의 쌍(그리드 포인트)을 생성하는 메서드 `meshgrid` 함수로 x축과 y축의 점들로 사각형의 영역을 나타내는 조합을 생성

In [2]:
import numpy as np

In [4]:
x = np.arange(3)
x

array([0, 1, 2])

In [5]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [7]:
X, Y = np.meshgrid(x, y)
X, Y

(array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]))

In [8]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

### 벡터화 연산
numpy 배열은 반복문을 쓰지않고 배열에 대하여 벡터 연산을 할 수 있음

In [35]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [36]:
%%time
z = np.zeros_like(x)
for index in range(len(x)):
  z[index] = x[index] + y[index]

CPU times: total: 0 ns
Wall time: 2.99 ms


In [37]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [41]:
x = np.arange(5)
y = np.arange(10, 15)
z = np.arange(5)

In [44]:
np.all(x == y)

False

In [45]:
np.all(x == z)

True

In [46]:
np.all(x <= y)

True

In [47]:
x

array([0, 1, 2, 3, 4])

In [50]:
10 * x

array([ 0, 10, 20, 30, 40])

In [49]:
10 ** x

array([    1,    10,   100,  1000, 10000], dtype=int32)

### 브로드 캐스팅
차원이 서로 다른 배열을 연산하는 기능  
, 부족한 차원에 대하여 반복 확장하여 큰 배열의 크기에 맞춘 후 연산을 진행

In [58]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [59]:
x + 1

array([1, 2, 3, 4, 5])

In [61]:
x = np.arange(15)
x = x.reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [63]:
x + y

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18]])

In [71]:
y = np.arange(3)
y = y.reshape(3, 1)
y

array([[0],
       [1],
       [2]])

In [72]:
x + y

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16]])

### 차원 축소 연산  
배열의 하나의 행을 하나의 집합으로 보고 그 집합에 대한 집계 처리 결과로 새로운 값을 반환하여 배열을 생성

In [79]:
x = np.arange(10)
x = x.reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
x.max() # 배열 전체 내 max 값 구하기

9

In [83]:
x.min() # 배열 전체 내 min 값 구하기

0

In [84]:
x.mean() # 배열 전체 내 평균 값 구하기

4.5

In [92]:
x.sum(axis=0) # 열 연산

array([ 5,  7,  9, 11, 13])

In [93]:
x.sum(axis=1) # 행 열산

array([10, 35])

### 정렬
- `sort` 메서드로 배열을 정렬 할 수 있음  
- `axis` 매개변수로 정렬 기준을 정할 수 잇음
- `axis=0` : 행을 따로 분리하여 정렬
- `axis=1` : 열을 따로 분리하여 정렬
- `axis`를 지정하지 않으면 0 과 같음

In [108]:

x = np.array([
  [5, 2, 7, 4],
  [11, 8, 6, 5],
  [8, 5, 11, 2]
])
x

array([[ 5,  2,  7,  4],
       [11,  8,  6,  5],
       [ 8,  5, 11,  2]])

In [110]:
x.sort() # 행 정렬
x

array([[ 2,  2,  5,  6],
       [ 4,  5,  7,  8],
       [ 5,  8, 11, 11]])

In [109]:
x.sort(axis=0) # 열 정렬
x

array([[ 5,  2,  6,  2],
       [ 8,  5,  7,  4],
       [11,  8, 11,  5]])

In [105]:
x.sort(axis=1) # 행 정렬
x

array([[ 2,  2,  5,  6],
       [ 4,  5,  7,  8],
       [ 5,  8, 11, 11]])

In [113]:
np.argsort(x, axis=0)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]], dtype=int64)

In [121]:
float_array = np.array([
      [5, 11, 12],
      [0, 18, 22],
      [8, 2, 7]], dtype='f')
float_array

array([[ 5., 11., 12.],
       [ 0., 18., 22.],
       [ 8.,  2.,  7.]], dtype=float32)

In [122]:
np.max(float_array) # 전체의 최댓값

22.0

In [123]:
np.sum(float_array, axis=1) # 각 행의 합

array([28., 40., 17.], dtype=float32)

In [124]:
np.max(float_array, axis=1) # 각 행의 최댓값

array([12., 22.,  8.], dtype=float32)

In [125]:
np.mean(float_array, axis=0) # 각 열의 평균

array([ 4.3333335, 10.333333 , 13.666667 ], dtype=float32)

In [126]:
np.min(float_array, axis=0) # 각 열의 최솟값

array([0., 2., 7.], dtype=float32)