### 2차원 그리드 포인트 생성
좌표값의 쌍(그리드 포인트)을 생성하는 메서드 `meshgrid` 함수로 x축과 y축의 점들로 사각형의 영역을 나타내는 조합을 생성

In [2]:
import numpy as np

In [4]:
x = np.arange(3)
x

array([0, 1, 2])

In [5]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [7]:
X, Y = np.meshgrid(x, y)
X, Y

(array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]))

In [8]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

### 벡터화 연산
numpy 배열은 반복문을 쓰지않고 배열에 대하여 벡터 연산을 할 수 있음

In [35]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [36]:
%%time
z = np.zeros_like(x)
for index in range(len(x)):
  z[index] = x[index] + y[index]

CPU times: total: 0 ns
Wall time: 2.99 ms


In [37]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [41]:
x = np.arange(5)
y = np.arange(10, 15)
z = np.arange(5)

In [44]:
np.all(x == y)

False

In [45]:
np.all(x == z)

True

In [46]:
np.all(x <= y)

True

In [47]:
x

array([0, 1, 2, 3, 4])

In [50]:
10 * x

array([ 0, 10, 20, 30, 40])

In [49]:
10 ** x

array([    1,    10,   100,  1000, 10000], dtype=int32)

### 브로드 캐스팅

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

NameError: name 'loga' is not defined